name: Publish

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      version:
        description: 'Increment version by'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      confirm:
        description: 'Type `yes` to confirm publish action into the VS Code Marketplace'
        required: true
        type: string

jobs:
  publish:
    if: inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Display input values
        run: |
          echo "Version: $VERSION"
          echo "Confirm: $CONFIRM"
        env:
          VERSION: ${{ inputs.version }}
          CONFIRM: ${{ inputs.confirm }}

      - run: yarn install --frozen-lockfile
      - run: yarn compile
      - run: yarn lint
      - run: yarn test
      - run: yarn package
      - run: yarn run publish --pat ${{ secrets.VSCE_PAT }} ${{ inputs.version }}
